---
title: "Explore data from postgis"
output: html_document
---

If you have generated the raw land designations dataset using the [designatedlands](https://github.com/bcgov/designatedlands) tool, then you have 
the postgis database on your computer, and you can explore it from R.

First connect to the database with the settings below 
(these are set by the `designatedlands` tool).

```{r warning=FALSE, message=FALSE}
library(rpostgis)
library(DT)

drv <- DBI::dbDriver("PostgreSQL")

con <- dbConnect(drv, dbname = "designatedlands", 
                 host = "localhost", user = "postgres", password = "postgres")


dbListTables(con)
dbTableInfo(con, "des_eco_overlay")
dbTableInfo(con, "a29_rec_site")
```

```{sql connection=con, max.print=NA, output.var="prot_summary"}
with a AS(
SELECT 
  category,
  ecoregion_name as ecoregion,
  sum(st_area(geom)) as area
FROM 
  des_eco_overlay
WHERE 
  bc_boundary = 'a00_bc_boundary_land_tiled'
  and category IS NOT NULL
GROUP BY 
  ecoregion_name, 
  category
), 

b AS(
SELECT 
  ecoregion_name as ecoregion,
  sum(st_area(geom)) as total_area
FROM 
  des_eco_overlay
WHERE 
  bc_boundary = 'a00_bc_boundary_land_tiled'
GROUP BY 
  ecoregion_name) 

SELECT
  a.category,
  a.ecoregion,
  a.area,
  b.total_area,
  round(CAST((area / total_area) * 100 as numeric), 2) as percent
FROM
  a LEFT JOIN b ON a.ecoregion = b.ecoregion
ORDER BY
  percent DESC;
```

```{r}
DT::datatable(prot_summary)
```


```{sql connection=con}
-- Check status of recreation sites
SELECT
LIFE_CYCLE_STATUS_CODE as code,
  COUNT(DISTINCT ogc_fid) as count
FROM a29_rec_site
WHERE RETIREMENT_DATE IS NULL 
GROUP BY 
LIFE_CYCLE_STATUS_CODE
```

```{sql connection=con}
SELECT 
 designation,
 substring(designation from 2) as des
FROM designatedlands_overlaps
LIMIT 500
```

```{r warning=FALSE}
dbSendQuery(con, "DROP TABLE IF EXISTS test")
dbWriteTable(con, "test", 
             data.frame(name = c("a1_foo", "b25_foo", "c9foo", "d5_bar", "1a"), 
                        id = 1:5))
```


```{sql connection=con}
SELECT * 
FROM test
```

```{sql connection=con}
UPDATE test
SET name = substring(name from 2)
WHERE name ~ '^[a-c][0-9]';

UPDATE test
SET name = '1_foobar'
WHERE name LIKE '%1_foo%';
```

```{sql connection=con}
SELECT * 
FROM test
ORDER BY id
```
